In [1]:
import numpy as np

In [42]:
a_i = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

In [43]:
b_i = np.array([[1, 2, 3 , 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14 ,15, 16]])

In [10]:
p = np.matmul(a_i[:,0], b_i)

In [28]:
p = np.array([p]).T

In [37]:
c_i = np.array([[]], dtype=np.int64).reshape(4, 0)

In [40]:
c_i = np.hstack((c_i, p))

In [41]:
c_i

array([[214, 214],
       [236, 236],
       [258, 258],
       [280, 280]])

In [59]:
k_i = np.array([], dtype=np.int64).reshape(0, 4)

In [60]:
for p in a_i:
    ll = np.matmul(p, b_i)
    print(ll)
    k_i = np.vstack((k_i, ll))

[ 90 100 110 120]
[174 196 218 240]
[258 292 326 360]


In [61]:
k_i

array([[ 90, 100, 110, 120],
       [174, 196, 218, 240],
       [258, 292, 326, 360]])

In [62]:
np.array([ np.matmul(p, b_i) for p in a_i ])

array([[ 90, 100, 110, 120],
       [174, 196, 218, 240],
       [258, 292, 326, 360]])

In [12]:
data = np.random.randint(-5000, 5000, size=(1000, 20))

In [13]:
with open('data.csv', 'w') as f:
    for row in data:
        f.write(','.join([str(x) for x in row]) + '\n')

In [3]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([10, 11, 12])

np.concatenate((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
an = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.dot(an, np.array([1, 2, 3]))

array([14, 32, 50])

In [4]:
np.linalg.norm(np.array([1, 2, -2]))

3.0

In [3]:
enc = np.array([[-97, 99, 72, -92, 49, -97, -55, 99, 58, 88, -66, 21, 8, 83, 29, -3, 86, -87, -48, 25],
[-78, 28, -58, -89, 87, -56, 32, 88, 16, 36, 46, 94, 62, -82, 59, -58, -14, 63, 71, -60],
[-29, -65, 30, 52, 8, -54, 58, -51, 17, -16, -35, -44, -35, -45, -4, 4, 95, 43, -56, 39],
[-19, 55, -2, -63, 12, -72, -59, 22, -64, -1, 88, 64, 24, -8, 87, 59, 32, -22, 15, 56],
[3, 26, -65, 6, 39, 38, -39, -11, 69, -87, 87, -81, -25, -53, 56, -92, -5, 75, -27, 48],
[43, 33, -30, -40, 38, -72, 7, -74, 31, 7, 45, 24, 61, 57, 18, -91, -38, 42, -42, 55],
[99, -45, 30, -65, 58, -90, 20, -26, -4, 60, 21, -3, 19, -73, 32, 43, -55, 30, -3, -31]])

dec = np.array([[-78, 28, -58, -89, 87, -56, 32, 88, 16, 36, 46, 94, 62, -82, 59, -58, -14, 63, 71, -60],
[-59, -65, -28, 66, 60, 25, 29, -35, -19, 20, 37, -73, 9, -39, 30, 60, 0, -27, -87, 72],
[-29, -65, 30, 52, 8, -54, 58, -51, 17, -16, -35, -44, -35, -45, -4, 4, 95, 43, -56, 39],
[-19, 55, -2, -63, 12, -72, -59, 22, -64, -1, 88, 64, 24, -8, 87, 59, 32, -22, 15, 56],
[3, 26, -65, 6, 39, 38, -39, -11, 69, -87, 87, -81, -25, -53, 56, -92, -5, 75, -27, 48],
[43, 33, -30, -40, 38, -72, 7, -74, 31, 7, 45, 24, 61, 57, 18, -91, -38, 42, -42, 55],
[99, -45, 30, -65, 58, -90, 20, -26, -4, 60, 21, -3, 19, -73, 32, 43, -55, 30, -3, -31]])

qr = np.array([-73,  -6 ,-40  , 1 , 95, -92, -84, -78 ,-15,  73, -18 , 49, -30, -20 , 87 ,-60,  62,  94 ,-21,  23])

In [7]:
np.linalg.norm(enc - qr, axis=1)

array([358.44525384, 309.21513546, 280.9003382 , 288.77499892,
       321.23355989, 271.79220004, 315.65487482])

In [8]:
np.linalg.norm(dec - qr, axis=1)

array([309.21513546, 321.06852851, 280.9003382 , 288.77499892,
       321.23355989, 271.79220004, 315.65487482])

In [9]:
np.dot(enc, qr)

array([21303, 28364, 16611, 18875, 14266, 21448,  9685])